In [5]:
import os 
import matplotlib.pyplot as plt 
import joblib 
import numpy as np 

plt.style.use("fivethirtyeight")

In [6]:
class Perceptron:
    def __init__(self, eta: float= None, epochs: int=None):   #eta:=learning rate 
        self.weights= np.random.randn(3) * 1e-4        ###keep the weights small so u converge
        self.eta = eta 
        self.epochs = epochs #iterations
    def fit(self, X, y):    #fit method
        self.X = X
        self.y = y
        X_with_bias = np.c_[self.X,-np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}")
        

In [7]:
obj = Perceptron(eta=0.01,epochs=10)

In [8]:
obj.eta

0.01

In [9]:
obj.epochs

10

In [10]:
obj.weights

array([9.29331419e-05, 3.98108933e-05, 6.46832149e-05])

In [11]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [13]:
obj.fit(X,y)

X with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [14]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])